name: Continuous Integration

on:
  push:
  pull_request:
      branches:
        - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update packages
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y build-essential libcriterion-dev gcovr

      - name: Run tests
        run: make tests_run

  lint-coding-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull docker image
        run: docker pull ghcr.io/epitech/coding-style-checker

      - name: Run coding style checker
        run: docker run --rm -v $(pwd)/:/mnt/ -v $(pwd)/reports/:/mnt/reports/ ghcr.io/epitech/coding-style-checker /mnt/ /mnt/reports/

      - name: Display results
        run: |
          if [ -s reports/coding-style-reports.log ]; then
            echo -e "FOUND ERRORS:\n"
            cat reports/coding-style-reports.log
            exit 1
          else
            echo "No coding-style errors found."
          fi
